# .github/workflows/build_streflop_soft_arm64.yml
# Workflow to build the 'streflop' library in software float mode for ARM64 macOS
# v3: Add debugging and use explicit CMake -S and -B paths

name: Build Streflop (SoftFloat ARM64)

# Allow manual triggering from the GitHub Actions UI
on: workflow_dispatch

jobs:
  build:
    name: Build streflop lib (soft-float, arm64)
    # Use the latest standard macOS runner
    runs-on: macos-latest

    steps:
      - name: Checkout streflop code
        uses: actions/checkout@v4 # Use latest checkout action

      - name: List files in workspace (DEBUG)
        # See where CMakeLists.txt actually is after checkout
        run: ls -la ${{ github.workspace }}
        shell: bash

      - name: Create build directory
        run: mkdir build

      - name: Configure CMake
        # Use explicit -S (source) and -B (build) arguments for CMake
        # -S points to the root of the checkout (${{ github.workspace }})
        # -B points to the build directory we created (./build)
        run: |
          cmake -S ${{ github.workspace }} -B ./build \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_OSX_ARCHITECTURES=arm64 \
            -DCMAKE_C_FLAGS="-DSTREFLOP_SOFT" \
            -DCMAKE_CXX_FLAGS="-DSTREFLOP_SOFT" \
            -DBUILD_SHARED_LIBS=OFF
        shell: bash

      - name: Build streflop library
        # Build using the specified build directory
        run: |
          cmake --build ./build --config Release -- -j$(sysctl -n hw.ncpu)
        shell: bash
        # Note: Changed 'make' to 'cmake --build' which is the modern way

      - name: Prepare artifact contents
        # Create a directory structure for the artifact
        # Include the static library and necessary headers
        run: |
          mkdir -p artifact/lib
          mkdir -p artifact/include
          # The library should now be in the build directory specified by -B
          cp build/libstreflop.a artifact/lib/
          # Copy headers from the source directory
          cp ${{ github.workspace }}/streflop.h artifact/include/
          # Add other necessary headers if SoftFloatWrapper.h etc. are needed by engine
          # cp ${{ github.workspace }}/SoftFloatWrapper.h artifact/include/ # Example
          # cp ${{ github.workspace }}/FPUSettings.h artifact/include/ # Example
        shell: bash

      - name: Upload streflop artifact
        # Upload the 'artifact' directory containing lib and headers
        uses: actions/upload-artifact@v4
        with:
          name: streflop-soft-arm64-lib # Name for the artifact
          path: artifact/ # Path to the directory to upload
